version: "3.1"
services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    networks:
      - backend
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: pedbot
  app:
    build: ./library-back-end
    container_name: app
    networks:
      - backend
      - frontend
    restart: always
    depends_on:
      - db
    ports:
      - 3001:3001
    volumes:
      - app:/usr/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  react:
    build: ./library-front-end
    container_name: react
    networks:
      - frontend
    restart: always
    ports:
      - 5173:5173
    volumes:
      - react:/usr/react
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
volumes:
  mysql_data:
  react:
  app:
networks:
  frontend:
    name: frontend
    driver: bridge
  backend:
    name: backend
    driver: bridge
